### ISSUE TITLE
Cant insert the photoshop css into css file 

### ISSUE THREAD

**Issue by cartknkr** [redaktorio/redaktor-issues#4]
Hi thank so much for create this tool very nice and awesome , really you guys are done well.

Here I am  asking how to insert the styles to css file after open photoshop in new window, I can easily export the images but every time I try to insert styles to css file while selecting the layer in the left side of psd, it showing css styles in right side the styleesheet option I selected the css file name and press insert mean its working fine, same thing i do for second time for different layer it is showing css styles but it is not appending the css file(file name) 

![image](https://cloud.githubusercontent.com/assets/4200629/21381156/b5f7a47e-c77f-11e6-874a-eb35d92915ad.png)

**Comment by redaktorio** [comment]
@cartknkr could you clarify what do you mean by
*i do for second time for different layer it is showing css styles but it is not appending the css file(file name)*

Do you mean appending CSS to *styles.css* works only the first time?

**Comment by redaktorio** [comment]
@cartknkr could you please refresh *ctrl + f5* and check the bug again.

**Comment by cartknkr** [comment]
Do you mean appending CSS to styles.css works only the first time?

yes correct, after I refresh psd page its working fine to append the css, again i try to add new layer styles to the  css file its not working(second time)

its working fine only first time , if  you want to add css to the styles.css file name then you have to refresh  the page each time. i tried it yesterday but forget to ask....

**Comment by cartknkr** [comment]
thanks boss css working fine :)

**Comment by redaktorio** [comment]
@cartknkr thank you for reporting the issue. If you find any feature missing you can open a feature request here as well.
